' Gambas module file

Public Sub abrir()

  Dim c As String
  Dim arr_cadenas As String[]
  Dim a As Integer
  Dim b As Integer
  Dim codigofinline As String
  Dim cuentaprov As Integer

  codigofinline = "|"
  Dialog.Title = "Seleccione un archivo para abrir"
  Dialog.Filter = ["", ""]
  Dialog.Path = User.Name
  Dialog.Filter = ["*.prov", "Datos de Proveedores"]

  If Not Dialog.OpenFile() Then
    Try arr_cadenas = Split(File.LOAD(Dialog.Path), codigofinline)

    If Error Then
      Message.Info("Error producido en la lectura del archivo ")
      Goto finabreproveedor
    End If

    If arr_cadenas[0] = "v0.0.1" Then
      FMain.TextBoxRutaProveedores.text = Dialog.Path
      var.Prov_numero = Val(arr_cadenas[2]) 'numero de proveedores que contiene el archivo
      b = 2
      'amplio memoria de los proveedores
      var.Prov_id.resize(var.Prov_numero)
      var.Prov_nombre.resize(var.Prov_numero)
      var.Prov_Nif.resize(var.Prov_numero)
      var.Prov_pc.resize(var.Prov_numero)   'persona de contacto
      var.Prov_telf.resize(var.Prov_numero)
      var.Prov_Fax.resize(var.Prov_numero)   'fax
      var.Prov_Movil.resize(var.Prov_numero)
      var.Prov_Correo.resize(var.Prov_numero)   'correo electronico
      var.Prov_fp.resize(var.Prov_numero)   'forma de pago
      var.Prov_Fecha.resize(var.Prov_numero)  'fecha del dato que introducimos
      var.Prov_Direccion.resize(var.Prov_numero)
      var.Prov_cp.resize(var.Prov_numero)
      var.Prov_Ciudad.resize(var.Prov_numero)
      var.Prov_Provincia.resize(var.Prov_numero)
      var.Prov_observaciones.resize(var.Prov_numero)
      var.provmemoria.resize(var.Prov_numero)

      'escribo datos de proveedores
      For a = 0 To var.Prov_numero - 1
        b += 1
        var.Prov_id[a] = arr_cadenas[b]
        b += 1
        var.Prov_nombre[a] = arr_cadenas[b]
        b += 1
        var.Prov_Nif[a] = arr_cadenas[b]
        b += 1
        var.Prov_pc[a] = arr_cadenas[b]
        b += 1
        var.Prov_telf[a] = arr_cadenas[b]
        b += 1
        var.Prov_Fax[a] = arr_cadenas[b]
        b += 1
        var.Prov_Movil[a] = arr_cadenas[b]
        b += 1
        var.Prov_Correo[a] = arr_cadenas[b]
        b += 1
        var.Prov_fp[a] = arr_cadenas[b]
        b += 1
        var.Prov_Fecha[a] = Val(arr_cadenas[b])
        b += 1
        var.Prov_Direccion[a] = arr_cadenas[b]
        b += 1
        var.Prov_cp[a] = arr_cadenas[b]
        b += 1
        var.Prov_Ciudad[a] = arr_cadenas[b]
        b += 1
        var.Prov_Provincia[a] = arr_cadenas[b]
        b += 1
        var.Prov_observaciones[a] = arr_cadenas[b]
      Next
      Message.Info("Archivo leido", "Aceptar")
      'muestro en gridproveedores
      BorradosDatosIniciales.dibujogridProveedores()
    Else
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      Goto finabreproveedor
    Endif

  End If
finabreproveedor:

End

'---------------------------------------------------------------------------------------------

Public Sub salva(Optional ruta As String, Optional sobreescribe As String)

  Dim lineas As String
  Dim destino As String
  Dim numArchivo As Integer
  Dim a As Integer
  Dim codigofinline As String
  Dim cuentaprov As Integer

inicio:
  var.esperaprov = "si"
  If ruta = "" Then
    Dialog.Title = "Escriba  un nombre de archivo para guardar los datos"
    Dialog.Filter = ["", ""]
    Dialog.Path = User.Name
    Dialog.Filter = ["*.prov", "Datos de Proveedores"]
    a = Dialog.SaveFile()
    If a = -1 Then Goto fins

    If Right$(Dialog.Path, 5) <> ".prov" Then
      destino = Dialog.Path & ".prov"
    Else
      destino = Dialog.Path
    End If

  Else
    destino = ruta
  Endif

  If sobreescribe = "sobreescribe" Then Goto finsobreescribe

  'Comprueba si existe el archivo, en tal caso pide confirmacion de sobreescritura
  If AbreGuardaProveedores.compruebaexistencia(DESTINO, "Proveedor") = 2 Then
    Goto inicio
  End If

finsobreescribe:

  'Message.Info("GRAVANDO DATOS")

  codigofinline = "|"
  lineas = "v0.0.1" & codigofinline 'informo version
  Lineas &= "gestionalmacen.090409" & codigofinline ' programa que ha echo el archivo

  'cuento cuantos proveedores no estan borrados para indicar el numero real de proveedores existentes
  cuentaprov = 0
  For a = 0 To var.Prov_numero - 1
    If var.Prov_id[a] <> "IdB" Then cuentaprov += 1
  Next

  Lineas &= Str$(cuentaprov) & codigofinline 'numero de proveedores que contiene el archivo sin estar borrados
  'escribo datos de proveedores
  For a = 0 To var.Prov_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"
    If var.Prov_id[a] <> "IdB" Then
      'los datos borrados no los salvo
      Lineas &= var.Prov_id[a] & codigofinline
      Lineas &= var.Prov_nombre[a] & codigofinline
      Lineas &= var.Prov_Nif[a] & codigofinline
      Lineas &= var.Prov_pc[a] & codigofinline
      Lineas &= var.Prov_telf[a] & codigofinline
      Lineas &= var.Prov_Fax[a] & codigofinline
      Lineas &= var.Prov_Movil[a] & codigofinline
      Lineas &= var.Prov_Correo[a] & codigofinline
      Lineas &= var.Prov_fp[a] & codigofinline
      Lineas &= Str$(var.Prov_Fecha[a]) & codigofinline
      Lineas &= var.Prov_Direccion[a] & codigofinline
      Lineas &= var.Prov_cp[a] & codigofinline
      Lineas &= var.Prov_Ciudad[a] & codigofinline
      Lineas &= var.Prov_Provincia[a] & codigofinline
      Lineas &= var.Prov_observaciones[a] & codigofinline
    End If
  Next
  If destino = "" Then
    Message.Info("No se pudo salvar")
    Goto fins

  Endif
  File.Save(destino, lineas)

  FMain.TextBoxRutaProveedores.text = destino

  If sobreescribe = "sobreescribe" Then
    FMain.ProgressBarGuardar.value = FMain.ProgressBarGuardar.value + 0.33
    Goto fins
  Endif

  If ruta <> "" Then Message.Info("Archivo salvado", "Aceptar")

  '
fins:
  var.esperaprov = ""

End

'------------------------------------------------------------------------------------
Public Function compruebaexistencia(destino As String, tipo As String) As Integer

  Dim DEVUELVE As Integer
  'EXIST DEVUELVE TRUE SI ESISTE EL ARCHIVO
  If Exist(destino) = False Then
    'no existe el archivo, por lo tanto podemos continuar con el salvado con el mismo nombre

    Return 1
  End If
  'esta parte se ejecuta cuando existe el archivo.
  If Message.Warning("Existe el archivo de " & tipo, "Cancelar", "Sobreescribir") = 1 Then
    ' HE CANCELADO
    Return 2
  End If

  If Message.Warning("Ha decidido sobreescribir ¿esta seguro?", "Cancelar", "Aceptar") = 1 Then
    Return 2
  Else
    'el usuario quiere sobreescribir y esta seguro con ello ya que lo ha dicho dos veces
    Return 1
  End If

End
