' Gambas module file

'borrado de proveedores....

Public Sub dibujogridProveedores()

  Dim a As Integer
  Dim numero As Integer

  'FMain.GridViewProveedor.Clear
  FMain.GridViewProveedor.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.Prov_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.Prov_id[a] <> "IdB" Then
      numero += 1
      FMain.GridViewProveedor.Rows.count = numero
      FMain.GridViewProveedor[numero - 1, 0].text = var.Prov_id[a]
      FMain.GridViewProveedor[numero - 1, 1].text = var.Prov_nombre[a]
      FMain.GridViewProveedor[numero - 1, 2].text = var.Prov_Nif[a]
      FMain.GridViewProveedor[numero - 1, 3].text = var.Prov_pc[a]
      FMain.GridViewProveedor[numero - 1, 4].text = var.Prov_telf[a]
      FMain.GridViewProveedor[numero - 1, 5].text = var.Prov_Fax[a]
      FMain.GridViewProveedor[numero - 1, 6].text = var.Prov_Movil[a]
      FMain.GridViewProveedor[numero - 1, 7].text = var.Prov_Correo[a]
      FMain.GridViewProveedor[numero - 1, 8].text = var.Prov_fp[a]
      FMain.GridViewProveedor[numero - 1, 9].text = var.Prov_Fecha[a]
      FMain.GridViewProveedor[numero - 1, 10].text = var.Prov_Direccion[a]
      FMain.GridViewProveedor[numero - 1, 11].text = var.Prov_cp[a]
      FMain.GridViewProveedor[numero - 1, 12].text = var.Prov_Ciudad[a]
      FMain.GridViewProveedor[numero - 1, 13].text = var.Prov_Provincia[a]
      FMain.GridViewProveedor[numero - 1, 14].text = var.Prov_observaciones[a]
    End If
  Next

  fmain.GridViewProveedor.ScrollY = (numero - 1) * 100

End

'borrado de conceptos....

Public Sub dibujogridconceptos(obra As String)

  Dim a As Integer
  Dim numero As Integer

  FMain.GridViewConceptos.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.concepto_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.concepto_id[a] <> "IdB" And var.concepto_Obra[a] = obra Then
      numero += 1
      FMain.GridViewConceptos.Rows.count = numero
      FMain.GridViewConceptos[numero - 1, 0].text = var.concepto_id[a]
      FMain.GridViewConceptos[numero - 1, 1].text = var.concepto_obra[a]
      FMain.GridViewConceptos[numero - 1, 2].text = var.concepto_idudobra[a]
      FMain.GridViewConceptos[numero - 1, 3].text = var.concepto_ud[a]
      FMain.GridViewConceptos[numero - 1, 4].text = var.concepto_nombre[a]
      FMain.GridViewConceptos[numero - 1, 5].text = redondea.numero(var.concepto_med[a])
      FMain.GridViewConceptos[numero - 1, 5].Alignment = 2
      FMain.GridViewConceptos[numero - 1, 6].text = redondea.numero(var.concepto_precio[a])
      FMain.GridViewConceptos[numero - 1, 6].Alignment = 2
      FMain.GridViewConceptos[numero - 1, 7].text = var.conceptotipo[a]
    End If
  Next

  fmain.GridViewConceptos.ScrollY = (numero - 1) * 100

End

'----------------------------------------------------------------

Public Sub dibujogrid1()

  Dim a As Integer
  Dim numero As Integer

  FfiltroProveedor.GridView1.columns.Count = 15
  FfiltroProveedor.GridView1.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.prov_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.concepto_id[a] <> "IdB" Then
      numero = numero + 1

      FfiltroProveedor.GridView1.Rows.count = numero
      FfiltroProveedor.GridView1[numero - 1, 0].text = var.Prov_id[a]
      FfiltroProveedor.GridView1[numero - 1, 1].text = var.Prov_nombre[a]
      FfiltroProveedor.GridView1[numero - 1, 2].text = var.Prov_Nif[a]
      FfiltroProveedor.GridView1[numero - 1, 3].text = var.Prov_pc[a]
      FfiltroProveedor.GridView1[numero - 1, 4].text = var.Prov_telf[a]
      FfiltroProveedor.GridView1[numero - 1, 5].text = var.Prov_Fax[a]
      FfiltroProveedor.GridView1[numero - 1, 6].text = var.Prov_Movil[a]
      FfiltroProveedor.GridView1[numero - 1, 7].text = var.Prov_Correo[a]
      FfiltroProveedor.GridView1[numero - 1, 8].text = var.Prov_fp[a]
      FfiltroProveedor.GridView1[numero - 1, 9].text = var.Prov_Fecha[a]
      FfiltroProveedor.GridView1[numero - 1, 10].text = var.Prov_Direccion[a]
      FfiltroProveedor.GridView1[numero - 1, 11].text = var.Prov_cp[a]
      FfiltroProveedor.GridView1[numero - 1, 12].text = var.Prov_Ciudad[a]
      FfiltroProveedor.GridView1[numero - 1, 13].text = var.Prov_Provincia[a]
      FfiltroProveedor.GridView1[numero - 1, 14].text = var.Prov_observaciones[a]
    End If
  Next

End

'filtro proveedor para facturas....

Public Sub dibujogrid11()

  Dim a As Integer
  Dim numero As Integer

  FfiltroProveedorFactura.GridView1.columns.Count = 15
  FfiltroProveedorFactura.GridView1.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.prov_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.concepto_id[a] <> "IdB" Then
      numero = numero + 1

      FfiltroProveedorFactura.GridView1.Rows.count = numero
      FfiltroProveedorFactura.GridView1[numero - 1, 0].text = var.Prov_id[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 1].text = var.Prov_nombre[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 2].text = var.Prov_Nif[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 3].text = var.Prov_pc[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 4].text = var.Prov_telf[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 5].text = var.Prov_Fax[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 6].text = var.Prov_Movil[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 7].text = var.Prov_Correo[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 8].text = var.Prov_fp[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 9].text = var.Prov_Fecha[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 10].text = var.Prov_Direccion[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 11].text = var.Prov_cp[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 12].text = var.Prov_Ciudad[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 13].text = var.Prov_Provincia[a]
      FfiltroProveedorFactura.GridView1[numero - 1, 14].text = var.Prov_observaciones[a]
    End If
  Next

End

' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' albaran
' - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Public Sub dibujogridAlbaran(obra As String)

  Dim a As Integer
  Dim numero As Integer

  'FMain.GridViewalbaran.Clear
  FMain.GridViewalbaran.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.alb_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.alb_id[a] <> "IdB" And var.alb_idobra[a] = obra Then
      numero += 1
      fmain.gridviewalbaran.Rows.count = numero
      fmain.gridviewalbaran[numero - 1, 0].text = var.alb_idobra[a]
      fmain.gridviewalbaran[numero - 1, 1].text = var.alb_prov[a]
      fmain.gridviewalbaran[numero - 1, 2].text = var.alb_id[a]
      fmain.gridviewalbaran[numero - 1, 3].text = var.alb_numeroprov[a]
      var.alb_valor[a] = buscar.sumadescompuesto(var.alb_id[a])

      fmain.gridviewalbaran[numero - 1, 4].text = Format(Round(var.alb_valor[a], -2), "#.#0")
      fmain.GridViewAlbaran[numero - 1, 4].Alignment = 2
      fmain.gridviewalbaran[numero - 1, 5].text = Format$(var.alb_fecha[a], "dd/mm/yyyy")
      fmain.gridviewalbaran[numero - 1, 6].text = Format$(var.alb_fechaEnt[a], "dd/mm/yyyy")
      fmain.gridviewalbaran[numero - 1, 7].text = var.alb_imp[a]

    End If
  Next
  fmain.GridViewalbaran.ScrollY = (numero - 1) * 100

End

'------------------------------------------------------------------------------
Public Sub dibujogridconceptos2(obra As String)

  Dim a As Integer
  Dim numero As Integer

  'FfiltroConceptos.GridViewfiltroconcepto.Columns.count = 8
  Titulos.filtroconceptos()

  FfiltroConceptos.GridViewfiltroconcepto.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.concepto_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.concepto_id[a] <> "IdB" Then

      If var.concepto_obra[a] = obra Then
        numero += 1
        FfiltroConceptos.GridViewfiltroconcepto.Rows.count = numero
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 0].text = var.concepto_id[a]
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 1].text = var.concepto_obra[a]
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 2].text = var.concepto_idudobra[a]
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 3].text = var.concepto_ud[a]
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 4].text = var.concepto_nombre[a]
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 5].text = redondea.numero(var.concepto_med[a])
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 6].text = redondea.numero(var.concepto_precio[a])
        FfiltroConceptos.GridViewfiltroconcepto[numero - 1, 7].text = var.conceptotipo[a]
      End If
    End If
  Next

End

'--------------------------------------------------------------------------
Public Sub dibujogridconceptosEntrada()

  Dim a As Integer
  Dim numero As Integer

  Titulos.entradas()

  FentradasAlb.GridViewConceptosEntrada.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.concepto_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.concepto_id[a] <> "IdB" Then
      numero += 1
      FentradasAlb.GridViewConceptosEntrada.Rows.count = numero
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 0].text = var.concepto_id[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 1].text = var.concepto_obra[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 2].text = var.concepto_idudobra[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 3].text = var.concepto_ud[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 4].text = var.concepto_nombre[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 5].text = redondea.numero(var.concepto_med[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 6].text = redondea.numero(var.concepto_precio[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 7].text = var.conceptotipo[a]
    End If
  Next
  FentradasAlb.GridViewConceptosEntrada.ScrollY = (numero - 1) * 100

End
'-----------------------------------------------------------------------------------
'relleno de grid de entradas de albaran

Public Sub dibujogridEntradaAlbaran(idalbaran As String)

  Dim a As Integer
  Dim numero As Integer
  Dim valoralbaran As Float

  Titulos.entradas()
  valoralbaran = 0

  FentradasAlb.GridViewConceptosEntrada.Rows.count = 0

  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.entrada_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If var.entrada_idconcepto[a] <> "IdB" And idalbaran = var.entrada_id[a] Then
      numero += 1
      FentradasAlb.GridViewConceptosEntrada.Rows.count = numero
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 0].text = var.entrada_id[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 1].text = var.entrada_idconcepto[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 2].text = buscaObra(var.entrada_idconcepto[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 3].text = buscaUd(var.entrada_idconcepto[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 4].text = buscaDenoConcepto(var.entrada_idconcepto[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 5].text = redondea.numero(var.entrada_medidaconcepto[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 6].text = redondea.numero(var.entrada_precio[a])
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 7].text = var.entrada_tipoprecio[a]
      FentradasAlb.GridViewConceptosEntrada[numero - 1, 8].text = buscaConceptoTipo(var.entrada_idconcepto[a])
      valoralbaran += var.entrada_medidaconcepto[a] * var.entrada_precio[a]
    End If
  Next

  FentradasAlb.GridViewConceptosEntrada.ScrollY = (numero - 1) * 100
  FentradasAlb.label2valoracion.text = redondea.numero(valoralbaran)

End

'busqueda
Public Sub buscaObra(idconcepto As String) As String 'devuelve la obra

  Dim a As Integer

  For a = 0 To var.concepto_numero - 1
    If var.concepto_id[a] = idconcepto Then
      Return var.concepto_obra[a]
    End If
  Next
  Message.Info("No encuentro obra del concepto: " & idconcepto)

End

Public Sub buscaUd(idconcepto As String) As String 'devuelve la unidad de concepto

  Dim a As Integer

  For a = 0 To var.concepto_numero - 1
    If var.concepto_id[a] = idconcepto Then
      Return var.concepto_ud[a]
    End If
  Next
  Message.Info("No encuentro unidad del concepto: " & idconcepto)

End

Public Sub buscaConceptoTipo(idconcepto As String) As String

  Dim a As Integer

  For a = 0 To var.concepto_numero - 1
    If var.concepto_id[a] = idconcepto Then
      Return var.conceptotipo[a]
    End If
  Next
  Message.Info("No encuentro el tipo de concepto de: " & idconcepto)

End

Public Sub buscaDenoConcepto(idconcepto As String) As String 'devuelvo la denominacion del concepto

  Dim a As Integer

  For a = 0 To var.concepto_numero - 1
    If var.concepto_id[a] = idconcepto Then
      Return var.concepto_nombre[a]
    End If
  Next
  Message.Info("No encuentro descripcion del concepto: " & idconcepto)

End

'-------------------------------------------------------------------------------------------------------------

Public Sub dibujogridConceptosSalidas(obra As String)

  Dim a As Integer
  Dim c As Integer
  Dim lineas As String
  Dim numero As Integer
  Dim sumaentrada As Float
  Dim sumasalida As Float
  Dim validar As Boolean

  FMain.GridViewConceptosSalidas.Rows.count = 0
  If var.entrada_numero = 0 Then
    Goto finnext
  Endif

  For a = 0 To var.concepto_numero - 1
    sumaentrada = 0
    For c = 0 To var.entrada_numero - 1
      validar = var.entrada_idconcepto[c] <> "IdB" And var.concepto_id[a] = var.entrada_idconcepto[c] 'AND var.concepto_Obra[a] = obra
      If validar Then
        sumaentrada += var.entrada_medidaconcepto[c]
      Endif
    Next

    If sumaentrada = 0 Then
      Goto finnexta
    Endif

    If var.conceptotipo[a] = "materiales" Then
      If var.concepto_id[a] <> "IdB" Then

        Lineas = var.concepto_id[a]
        Lineas &= var.concepto_idudobra[a]
        Lineas &= var.concepto_nombre[a]
        Lineas &= var.concepto_ud[a]
        Lineas &= var.concepto_med[a]
        Lineas &= var.concepto_precio[a]
        'Lineas &= var.conceptomemoria[a]
        Lineas &= var.conceptotipo[a]
        Lineas &= var.concepto_Obra[a]

        If dentro(Upper$(var.concepto_Obra[a]), Upper$(obra)) Then

          'entradas de mediciones
          sumaentrada = 0
          For c = 0 To var.entrada_numero - 1
            If var.entrada_idconcepto[c] <> "IdB" And var.concepto_id[a] = var.entrada_idconcepto[c] Then
              sumaentrada += var.entrada_medidaconcepto[c]
            Endif
          Next

          'salidas anteriores de mediciones
          sumasalida = 0
          For c = 0 To var.entrada_numero - 1
            If var.entrada_idconcepto[c] <> "IdB" And var.concepto_id[a] = var.entrada_idconcepto[c] Then
              sumasalida += var.entrada_salida[c]
            Endif
          Next

          If (sumaentrada - sumasalida) = 0 Then
            'para que no escriba conceptos sin salidas

          Else
            numero += 1
            FMain.GridViewConceptosSalidas.Rows.count = numero
            FMain.GridViewConceptosSalidas[numero - 1, 0].text = var.concepto_id[a]
            ' FMain.GridViewConceptosSalidas[numero - 1, 1].text = var.concepto_id[a]
            FMain.GridViewConceptosSalidas[numero - 1, 2].text = var.concepto_Obra[a]
            FMain.GridViewConceptosSalidas[numero - 1, 3].text = var.concepto_idudobra[a]
            FMain.GridViewConceptosSalidas[numero - 1, 4].text = var.concepto_ud[a]
            FMain.GridViewConceptosSalidas[numero - 1, 5].text = var.concepto_nombre[a]
            FMain.GridViewConceptosSalidas[numero - 1, 6].text = redondea.numero(sumaentrada)
            FMain.GridViewConceptosSalidas[numero - 1, 6].Alignment = 2
            FMain.GridViewConceptosSalidas[numero - 1, 7].text = redondea.numero(sumasalida)
            FMain.GridViewConceptosSalidas[numero - 1, 7].Alignment = 2
            'pendiente
            FMain.GridViewConceptosSalidas[numero - 1, 8].text = redondea.numero(sumaentrada - sumasalida)
            FMain.GridViewConceptosSalidas[numero - 1, 8].Alignment = 2
          End If

        End If
      End If
    Endif

  finnexta:
  Next

finnext:

End

Sub dentro(frase As String, patron As String) As Boolean

  Return InStr(frase, patron)

End

'-------------------------------------------------------------
'dibujo albaran filtrado por obra y proveedor para facturas
'--------------------------------------------------------------
Public Sub dibujogridAlbaranProveedorObra(proveedor As String, obra As String, grid As GridView, fechalimiteimp As Date)

  Dim a As Integer
  Dim numero As Integer
  Dim validar As Boolean

  'FMain.GridViewalbaran.Clear
  Grid.Rows.count = 0

  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.alb_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"

    If Len(var.alb_imp[a]) > 0 Then Goto finnextalb

    'IF Mid$(var.alb_imp[a], 0, 2) = "Si" THEN GOTO finnextalb 'albaran imputado
    validar = var.alb_id[a] <> "IdB" And proveedor = var.alb_prov[a] And obra = var.alb_idobra[a] And var.alb_fecha[a] <= fechalimiteimp

    If validar Then
      numero += 1
      grid.Rows.count = numero
      grid[numero - 1, 0].text = var.alb_idobra[a] 'cuidado que estan ocultas
      grid[numero - 1, 1].text = var.alb_prov[a] 'cuidado que estan ocultas
      grid[numero - 1, 2].text = var.alb_id[a]
      grid[numero - 1, 3].text = var.alb_numeroprov[a]
      var.alb_valor[a] = buscar.sumadescompuesto(var.alb_id[a])

      grid[numero - 1, 4].text = var.alb_valor[a]
      grid[numero - 1, 5].text = Format$(var.alb_fecha[a], "dd/mm/yyyy")
      grid[numero - 1, 6].text = Format$(var.alb_fechaEnt[a], "dd/mm/yyyy")
      grid[numero - 1, 7].text = var.alb_imp[a]

    End If
  finnextalb:

  Next

  OrdenacionGridview.ord_AZ(grid, 3)

End

'--------------------------------------- rellenar el grid de factura
Public Sub dibujogridFactura(proveedor As String, obra As String)

  Dim a As Integer
  Dim numero As Integer

  FMain.GridViewfactura.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.fact_numero - 1
    If var.fact_id[a] <> "IdB" Then
      If var.fact_prov[a] = proveedor Then
        If var.fact_idobra[a] = obra Then
          numero += 1
          fmain.GridViewfactura.Rows.count = numero
          fmain.GridViewfactura[numero - 1, 0].text = var.fact_id[a]
          fmain.GridViewfactura[numero - 1, 1].text = var.fact_prov[a]
          fmain.GridViewfactura[numero - 1, 2].text = var.fact_nprov[a]
          fmain.GridViewFactura[numero - 1, 3].text = var.fact_idobra[a]
          fmain.GridViewfactura[numero - 1, 4].text = Format$(var.fact_fecha[a], "dd/mm/yyyy")
          fmain.GridViewfactura[numero - 1, 5].text = Format$(var.fact_fecha_imp[a], "dd/mm/yyyy")
          fmain.GridViewfactura[numero - 1, 6].text = var.fact_valor[a]
        End If
      End If
    End If
  Next

End

'dibujo los albaranes que esten asociados a la factura

Public Sub dibujogridAlbaranProveedorObraimp(idfactura As String, proveedor As String, obra As String, grid As GridView, fechalimiteimp As Date)

  Dim a As Integer
  Dim numero As Integer
  Dim sumavalorfactura As Float
  Dim validar As Boolean

  sumavalorfactura = 0
  'FMain.GridViewalbaran.Clear
  Grid.Rows.count = 0
  numero = 0 'contador de filas validas (sin estar borradas)

  For a = 0 To var.alb_numero - 1
    'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"
    If var.alb_imp[a] = "" Then Goto finnextalb 'albaran imputado

    If Mid$(var.alb_imp[a], 4, Len(var.alb_imp[a])) = idfactura Then
      validar = proveedor = var.alb_prov[a] And obra = var.alb_idobra[a] And var.alb_fecha[a] <= fechalimiteimp
      If validar Then
        numero += 1
        grid.Rows.count = numero
        grid[numero - 1, 0].text = var.alb_idobra[a]
        grid[numero - 1, 1].text = var.alb_prov[a]
        grid[numero - 1, 2].text = var.alb_id[a]
        grid[numero - 1, 3].text = var.alb_numeroprov[a]
        'recalcula la suma
        'var.alb_valor[a] = buscar.sumadescompuesto(var.alb_id[a])

        grid[numero - 1, 4].text = var.alb_valor[a]
        grid[numero - 1, 5].text = Format$(var.alb_fecha[a], "dd/mm/yyyy")
        grid[numero - 1, 6].text = Format$(var.alb_fechaEnt[a], "dd/mm/yyyy")
        grid[numero - 1, 7].text = var.alb_imp[a]
        sumavalorfactura += Escribe.comadecimal(CStr(var.alb_valor[a]))
      End If
    Endif
  finnextalb:
    fmain.ValueBoxValorFactura.value = sumavalorfactura

  Next

  OrdenacionGridview.ord_AZ(grid, 3)

End
