' Gambas module file

'---------------------------------------------------------
' DATOS DEL PROGRAMA
'---------------------------------------------------------

'DEFINICION DE VARIABLES
Public rutaprueba As String
Public version As String
Public programa As String
Public archivo_informacion_update As String

Public Sub cargadatos()

  UpdateDatos.rutaprueba = "http://www.proyectojulio.webcindario.com/home/julio/gestionalmacenTutorial/007/" 'poner siempre al final / (la barra invertida)
  UpdateDatos.version = "0.0.7.4.3r07" 'se pueden introducir las fechas haciendo click en fecha
  'con valoracion del albaran que introducimos
  'ordenacion de albaranes imputados en facturas
  'copiar albaranes imputados en facturas

  UpdateDatos.archivo_informacion_update = "archivo.update"
  UpdateDatos.programa = "gestionalmacen"

  FMain.caption = UpdateDatos.programa & " Version " & UpdateDatos.version

End
