' Gambas module file

'Sistema de comprobacion de version actualizada

Public Sub Update(ruta As String, archivo_update As String, programa As String, version_actual As String)
  'descargo archivo con la informacion de la actualizacion
  'desde ruta
  ' ejmplo de ruta: http://www.jusabejusabe.webcindario.com/index.html

  '
  Dim arr_cadenas As String[]
  Dim a As String
  Dim cadenas As String
  Dim salida As String 'texto que contiene la salida que genera el comando
  Dim comando As String
  Dim c As String
  Dim genera_salida As String
  Dim contador As Integer
  Dim contador2 As Integer
  Dim lectura As String[]

  'si existe borro el archivo archivo.update
  'comando = "cd " & User.home
  'ejecuta_comando(comando) 'v.008 ' para que este en el mismo directorio que donde se ejecute el programa principal

  comando = "rm " & User.home & "/" & archivo_update
  ejecuta_comando(comando) 'v.008

  comando = "wget -o " & User.home & "/" & "reporte.txt " & ruta & archivo_update
  ejecuta_comando(comando)

  comando = "mv reporte.txt " & User.Home 'nueva linea
  ejecuta_comando(comando) 'nueva linea

  lectura = Split(File.LOAD(User.home & "/reporte.txt"), "\n")

  FUpdate.TextArea1.text = ""

  For contador = 0 To lectura.Count - 1
    FUpdate.TextArea1.text &= lectura[contador] & "\n"
  Next

  'carga archivo update, para procesarlo

  Try arr_cadenas = Split(File.LOAD(User.home & "/" & archivo_update), "\n")

  If Error Then
    Message.Info("Error producido en la lectura del archivo de update. Debes de ejecutar el programa .gambas en el directorio /home/usuario ")
    Goto fin
  End If

  ' una vez descargado hay que leer el archivo de version
  '0: [version del programa]
  '1: nos indica el numero de la version
  '2: [nombre programa]
  '3: contiene el nombre del programa
  '4: [archivos a descargar]
  '5: archivo a descargar 1
  '6: archivo a descargar 2...

  'compara a que programa se refiere el archivo update
  If arr_cadenas[3] <> programa Then
    Message.Error(("El archivo de actualizacion no hace referencia a este programa"))
    Goto FIN
  End If

  ' compara la version del archivo en el servidor con la del programa actual
  If arr_cadenas[1] = version_actual Then
    Message.Info(("ya tienes la version mas actualizada"))
  Else
    If arr_cadenas[1] > version_actual Then
      FUpdate.ToolButton1.text = ("version en el servidor es mas actual.Descargandola en la ruta /home/usuario...")
      ' nota importante:
      ' para que puedas ejecutar la linea anterior sin error deben de ser publicos los formularios
      ' en el menu:
      ' Proyecto / Propiedades / Opciones / Los controles de formulario son publicos /
      ' elige Si
      For contador = 5 To arr_cadenas.Count - 1

        comando = "wget  -o " & User.home & "/" & "reporte.txt " & ruta & "/" & arr_cadenas[contador]
        ejecuta_comando(comando)

        lectura = Split(File.LOAD(User.home & "/reporte.txt"), "\n")

        FUpdate.TextArea1.text &= "\n"
        For contador2 = 0 To lectura.Count - 1
          FUpdate.TextArea1.text &= lectura[contador] & "\n"
        Next

      Next
    Else
      Message.Info(("la version del servidor es mas antigua"))

    End If

  End If

  'FMain.Textarea1.Text = cadenas

  ' nota importante:
  ' para que puedas ejecutar sin error esta linea debes en el menu:
  ' Proyecto / Propiedades / Opciones / Los controles de formulario son publicos / Si

fin:

  comando = "rm " & archivo_update 'borra el archivo update descargado"
  ejecuta_comando(comando) 'v.008

End

Public Sub ejecuta_comando(comando As String)

  Dim hproc As Process

  hproc = Shell comando
  'espero mientras se ejecuta el comando shell
  Do While hproc.state = process.running
    Wait 0.1
  Loop

End
