' Gambas module file

PUBLIC SUB salva()
DIM lineas AS String
DIM destino AS String
DIM numArchivo AS Integer
DIM a AS Integer
DIM codigofinline AS String


  
 ' FMain.TextBoxRutaConcepto.text = destino



  'salva proveedores

   AbreGuardaProveedores.salva(FMain.TextBoxRutaProveedores.text) 

espera1:
IF var.esperaprov = "si" THEN GOTO espera1



  'salva conceptos
AbreGuardaConcepto.salva(FMain.TextBoxRutaConcepto.text) 
espera2:
IF var.esperaconcepto = "si" THEN GOTO espera2

'salva facturas y albaranes
AbreGuardaAlbFact.salva(FMain.TextBoxRutaAlbFact.text) 

espera3:
IF var.esperaalb = "si" THEN GOTO espera3

inicio:
Dialog.Title = "Escriba  un nombre de archivo para guardar las rutas de la seccion"
Dialog.Filter = ["", ""]
Dialog.Path = User.Name

Dialog.Filter = ["*.seccion", "Datos de seccion"]
a = Dialog.SaveFile()
IF a = -1 THEN GOTO fins
  IF Right$(Dialog.Path, Len(".seccion")) <> ".seccion" THEN
      destino = Dialog.Path & ".seccion"
      ELSE
      destino = Dialog.Path
      END IF
      
      'Comprueba si existe el archivo, en tal caso pide confirmacion de sobreescritura
  IF AbreGuardaProveedores.compruebaexistencia(DESTINO, "Seccion") = 2 THEN
   GOTO inicio
   END IF
   
  codigofinline = "|"
  lineas = "v0.0.1" & codigofinline 'informo version
  Lineas &= "gestionalmacen.090409" & codigofinline ' programa que ha echo el archivo
  Lineas &= FMain.TextBoxRutaProveedores.Text & codigofinline 'numero de proveedores que contiene el archivo
  Lineas &= FMain.TextBoxRutaAlbFact.text & codigofinline 
  Lineas &= FMain.TextBoxRutaConcepto.Text & codigofinline 
  Lineas &= FMain.ComboBoxObras.Text & codigofinline 
  File.Save(destino, lineas)
  var.seccion = destino
 
  Message.Info("Archivos salvados", "Aceptar")
FMain.TextBoxRutaSeccion.Text = var.seccion

fins:

END

'--------------------------------------------------------------------------------
'
PUBLIC SUB abrir()
DIM c AS String
DIM arr_cadenas AS String[]
DIM a AS Integer
DIM b AS Integer
DIM codigofinline AS String
codigofinline = "|"
Dialog.Title = "Seleccione un archivo de seccion para abrir"
Dialog.Filter = ["", ""]
Dialog.Path = User.Name
Dialog.Filter = ["*.seccion", "Datos de seccion"]

IF NOT Dialog.OpenFile() THEN
var.seccion = Dialog.Path
  arr_cadenas = Split(File.LOAD(Dialog.Path), codigofinline)
  var.esperaprov = "si"
  var.esperaconcepto = "si"
  var.esperaalb = "si"
  
  IF arr_cadenas[0] = "v0.0.1" THEN 
        IF arr_cadenas[2] <> "" THEN abrirrutaproveedores(arr_cadenas[2])
        
        'esperar
        espera11:
        IF var.esperaprov = "si" THEN GOTO espera11
         
        IF arr_cadenas[4] <> "" THEN abrirrutaconceptos(arr_cadenas[4])
        'esperar
         espera22:
        IF var.esperaconcepto = "si" THEN GOTO espera22

         
        IF arr_cadenas[3] <> "" THEN AbreGuardaAlbFact(arr_cadenas[3])
        'esperar
        espera33:
        IF var.esperaalb = "si" THEN GOTO espera33
        

        FMain.ComboBoxObras.tag = arr_cadenas[5]
        ELSE
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      GOTO finabrir
      ENDIF 

END IF


finabrir:
END
' ----------------------------------------------------------------------------------

PUBLIC SUB abrirrutaproveedores(ruta AS String)
  DIM c AS String
DIM arr_cadenas AS String[]
DIM a AS Integer
DIM b AS Integer
DIM codigofinline AS String
codigofinline = "|"

TRY arr_cadenas = Split(File.LOAD(ruta), codigofinline)

IF ERROR THEN 
      Message.Info("Error producido en la lectura del archivo")
      GOTO finabreproveedor
      END IF



  IF arr_cadenas[0] = "v0.0.1" THEN 
        FMain.TextBoxRutaProveedores.text = ruta
         var.Prov_numero = Val(arr_cadenas[2]) 'numero de proveedores que contiene el archivo
          b = 2
        'amplio memoria de los proveedores
        var.Prov_id.resize(var.Prov_numero)
        var.Prov_nombre.resize(var.Prov_numero)
        var.Prov_Nif.resize(var.Prov_numero)
        var.Prov_pc.resize(var.Prov_numero)   'persona de contacto
        var.Prov_telf.resize(var.Prov_numero)
        var.Prov_Fax.resize(var.Prov_numero)   'fax
        var.Prov_Movil.resize(var.Prov_numero)  
        var.Prov_Correo.resize(var.Prov_numero)   'correo electronico
        var.Prov_fp.resize(var.Prov_numero)   'forma de pago
        var.Prov_Fecha.resize(var.Prov_numero)  'fecha del dato que introducimos
        var.Prov_Direccion.resize(var.Prov_numero)  
        var.Prov_cp.resize(var.Prov_numero)
        var.Prov_Ciudad.resize(var.Prov_numero)
        var.Prov_Provincia.resize(var.Prov_numero)
        var.Prov_observaciones.resize(var.Prov_numero)
        var.provmemoria.resize(var.Prov_numero)
        
        
        'escribo datos de proveedores
        FOR a = 0 TO var.Prov_numero - 1
          b += 1
          var.Prov_id[a] = arr_cadenas[b]
          b += 1
          var.Prov_nombre[a] = arr_cadenas[b]
          b += 1
          var.Prov_Nif[a] = arr_cadenas[b]
          b += 1 
          var.Prov_pc[a] = arr_cadenas[b]
          b += 1
          var.Prov_telf[a] = arr_cadenas[b]
          b += 1
          var.Prov_Fax[a] = arr_cadenas[b] 
          b += 1
          var.Prov_Movil[a] = arr_cadenas[b]
          b += 1
          var.Prov_Correo[a] = arr_cadenas[b]
          b += 1
          var.Prov_fp[a] = arr_cadenas[b]
          b += 1
          var.Prov_Fecha[a] = Val(arr_cadenas[b])
          b += 1
          var.Prov_Direccion[a] = arr_cadenas[b]
          b += 1
          var.Prov_cp[a] = arr_cadenas[b]
          b += 1
          var.Prov_Ciudad[a] = arr_cadenas[b] 
          b += 1
          var.Prov_Provincia[a] = arr_cadenas[b]
          b += 1
          var.Prov_observaciones[a] = arr_cadenas[b]
       NEXT
      'muestro en gridproveedores
      BorradosDatosIniciales.dibujogridProveedores()
      ELSE
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      GOTO finabreproveedor
      ENDIF 


finabreproveedor:
var.esperaprov = "no"
END

'---------------------------------------------------------------------------------
PUBLIC SUB AbreGuardaAlbFact(ruta AS String)
  DIM c AS String
DIM arr_cadenas AS String[]
DIM a AS Integer
DIM b AS Integer
DIM codigofinline AS String
codigofinline = "|"


  TRY arr_cadenas = Split(File.LOAD(ruta), codigofinline)
  IF ERROR THEN 
      Message.Info("Error producido en la lectura del archivo ")
      GOTO finabreconcepto
      END IF
  
  
  
  
  IF arr_cadenas[0] = "v0.0.1" THEN 
       FMain.TextBoxRutaAlbFact.text = ruta
        var.alb_numero = Val(arr_cadenas[2]) 'numero de conceptos que contiene el archivo
          b = 2
        'amplio memoria de los albaranes
     'redimensiono
    var.alb_id.Resize(var.alb_numero) 'id automatico del programa
    var.alb_numeroprov.resize(var.alb_numero) 'numro que tiene el albaran (lo pone el proveedor)
    var.alb_prov.resize(var.alb_numero)  'proveedor de este albaran
    var.alb_fecha.resize(var.alb_numero) 'fecha del albaran
    var.alb_idobra.Resize(var.alb_numero) 
    var.alb_imp.Resize(var.alb_numero)
    var.alb_fechaEnt.resize(var.alb_numero)   'entrada en obra
    var.albmemoria.resize(var.alb_numero)
    var.alb_valor.resize(var.alb_numero)
    'escribo datos de proveedores
        FOR a = 0 TO var.alb_numero - 1
          b += 1
          var.alb_id[a] = arr_cadenas[b]
          b += 1
          var.alb_numeroprov[a] = arr_cadenas[b]
          b += 1
          var.alb_prov[a] = arr_cadenas[b]
          b += 1 
          var.alb_fecha[a] = arr_cadenas[b]
          b += 1
          var.alb_idobra[a] = arr_cadenas[b]
          b += 1
          var.alb_imp[a] = arr_cadenas[b] 
          b += 1
          var.alb_fechaEnt[a] = arr_cadenas[b]
          b += 1
          var.albmemoria[a] = arr_cadenas[b]
          b += 1
          var.alb_valor[a] = arr_cadenas[b]
     NEXT
     'entradas de conceptos en albaranes
     b += 1
     var.entrada_numero = Val(arr_cadenas[b]) 
     
     
     'conceptos dentro de albaranes
        var.entrada_id.resize(var.entrada_numero)
        var.entrada_idconcepto.resize(var.entrada_numero)
        var.entrada_medidaconcepto.resize(var.entrada_numero) 'le ponga la medida del concepto que tiene el albaran
        var.entrada_precio.resize(var.entrada_numero) 'precio del cooncepto
        var.entrada_tipoprecio.resize(var.entrada_numero) ' contrado, estimacion, oferta
        var.entrada_memoria.resize(var.entrada_numero)   
        var.entrada_salida.Resize(var.entrada_numero)   
        
        FOR a = 0 TO var.entrada_numero - 1
          b += 1
          var.entrada_id[a] = arr_cadenas[b]
           b += 1
          var.entrada_idconcepto[a] = arr_cadenas[b]
           b += 1
          var.entrada_medidaconcepto[a] = arr_cadenas[b]
           b += 1
          var.entrada_precio[a] = arr_cadenas[b]
           b += 1
          var.entrada_tipoprecio[a] = arr_cadenas[b]
           b += 1
          var.entrada_memoria[a] = arr_cadenas[b]
           b += 1
          var.entrada_salida[a] = arr_cadenas[b]
     NEXT

'facturas
    
    b += 1
    var.fact_numero = Val(arr_cadenas[b]) 
    
    var.fact_id.Resize(var.fact_numero) 'id dado por el programa a cada factura introducida
    var.fact_prov.Resize(var.fact_numero) 'nombre del proveedor de esta factura
    var.fact_nprov.Resize(var.fact_numero) 'numero de factura que da n ºfacturadadaproveedor   (nº de factura que le da el proveedor)
    var.fact_idobra.Resize(var.fact_numero) 'obra a la que pertenece la factura
    var.fact_fecha.Resize(var.fact_numero) 'fecha de la factura (la que tiene la factura)
    var.fact_fecha_imp.Resize(var.fact_numero) 'fecha de imputacion factura
    var.fact_valor.Resize(var.fact_numero)
    
      FOR a = 0 TO var.fact_numero - 1
      b += 1
        var.fact_id[a] = arr_cadenas[b]
           b += 1
          var.fact_prov[a] = arr_cadenas[b]
           b += 1
          var.fact_nprov[a] = arr_cadenas[b]
           b += 1
          var.fact_idobra[a] = arr_cadenas[b]
           b += 1
          var.fact_fecha[a] = arr_cadenas[b]
           b += 1 
            var.fact_fecha_imp[a] = arr_cadenas[b]
           b += 1
            var.fact_valor[a] = arr_cadenas[b]
NEXT 
    '------------------------------------------------------------------
     ' final de lectura de archivo
     '-------------------------------------------------------------------
     
     FMain.TS1[2].Enabled = TRUE
     FMain.TS1[3].Enabled = TRUE 'albaranes
     FMain.TS1[4].Enabled = TRUE 'salidas
     FMain.TS1[5].Enabled = TRUE 'facturas
     FMain.TS1[6].enabled = TRUE 'informes 'bug corregido 007
     
      'Message.Info("Archivo leido", "Aceptar") 
      
      
      ELSE
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      GOTO finabreconcepto
      ENDIF 


finabreconcepto:
var.esperaalb = "no"
END



' --------------------------------------------------------------------------------
PUBLIC SUB abrirrutaconceptos(ruta AS String)
  DIM c AS String
DIM arr_cadenas AS String[]
DIM a AS Integer
DIM b AS Integer
DIM codigofinline AS String
codigofinline = "|"

  TRY arr_cadenas = Split(File.LOAD(ruta), codigofinline)
  
  IF ERROR THEN 
      Message.Info("Error producido en la lectura del archivo de update en el servidor")
      GOTO finabreconcepto
      END IF
  
  
  
  IF arr_cadenas[0] = "v0.0.1" THEN 
       FMain.TextBoxRutaConcepto.text = ruta
        var.concepto_numero = Val(arr_cadenas[2]) 'numero de conceptos que contiene el archivo
          b = 2
        'amplio memoria de los proveedores
        'conceptos
      var.concepto_id.Resize(var.concepto_numero)
      var.concepto_idudobra.resize(var.concepto_numero) 'unidad de obra donde se encuentra
      var.concepto_nombre.resize(var.concepto_numero) 'nombre descriptivo unidad
      var.concepto_ud.Resize(var.concepto_numero)
      var.concepto_med.resize(var.concepto_numero) 'medicion
      var.concepto_precio.resize(var.concepto_numero)   'precio de contrato
      var.conceptomemoria.resize(var.concepto_numero)
      var.conceptotipo.resize(var.concepto_numero)
      var.concepto_Obra.resize(var.concepto_numero)
        
        
        
        'escribo datos de proveedores
        FOR a = 0 TO var.concepto_numero - 1
          b += 1
          var.concepto_id[a] = arr_cadenas[b]
          b += 1
          var.concepto_idudobra[a] = arr_cadenas[b]
          b += 1
          var.concepto_nombre[a] = arr_cadenas[b]
          b += 1 
          var.concepto_ud[a] = arr_cadenas[b]
          b += 1
          var.concepto_med[a] = Escribe.comadecimal(arr_cadenas[b])
          b += 1
          var.concepto_precio[a] = Escribe.comadecimal(arr_cadenas[b])
          b += 1
          var.conceptotipo[a] = arr_cadenas[b]
          b += 1
          var.concepto_Obra[a] = arr_cadenas[b]
     NEXT
     FMain.TS1[2].Enabled = TRUE
    
      'muestro en gridproveedores
      
      ELSE
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      GOTO finabreconcepto
      ENDIF 

'abrir ruta albaranes y facturas
finabreconcepto:
var.esperaconcepto = "no"
END

'-----------------------------------------------------------


PUBLIC SUB abreseccionrutaconocida(rutareciente AS String)
DIM a AS Integer
DIM b AS Integer
DIM c AS String
DIM arr_cadenas AS String[]
DIM codigofinline AS String
codigofinline = "|"


var.seccion = rutareciente
  arr_cadenas = Split(File.LOAD(var.seccion), codigofinline)
  
  IF arr_cadenas[0] = "v0.0.1" THEN 
        IF arr_cadenas[2] <> "" THEN abrirrutaproveedores(arr_cadenas[2])
        
        'esperar
        espera11:
        IF var.esperaprov = "si" THEN GOTO espera11
         
        IF arr_cadenas[4] <> "" THEN abrirrutaconceptos(arr_cadenas[4])
        'esperar
         espera22:
        IF var.esperaconcepto = "si" THEN GOTO espera22

         
        IF arr_cadenas[3] <> "" THEN AbreGuardaAlbFact(arr_cadenas[3])
        'esperar
        espera33:
        IF var.esperaalb = "si" THEN GOTO espera33
        

        FMain.ComboBoxObras.tag = arr_cadenas[5]
        ELSE
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      GOTO finabrir3
      ENDIF 




''finabrir:

  IF var.concepto_numero = 0 AND var.Prov_numero = 0 THEN GOTO finabrir2
' codigo: obras de conceptos añadirlas a combo de obra...
'repetir tanta veces como conceptos haya
IF fmain.ComboBoxObras.CounT = 0 THEN 
     fmain.ComboBoxObras.Add(var.concepto_Obra[0])
    END IF
    
FOR a = 0 TO var.concepto_numero - 1
  FOR b = 0 TO fmain.ComboBoxObras.Count - 1
    IF Upper$(var.concepto_Obra[a]) = Upper$(fmain.ComboBoxObras[b].text) THEN GOTO finnextobrasconceptos22
  NEXT
fmain.ComboBoxObras.Add(var.concepto_Obra[a])
finnextobrasconceptos22:
NEXT 
  
'si no coincide con la lista de obra exitente, se incluye en la lista
fmain.ComboBoxObras.text = FMain.ComboBoxObras.tag 
fmain.TextBoxRutaSeccion.Text = var.seccion
fmain.salvadatosseccionactual.enabled = TRUE
var.inicioalbaranes = 0
var.inicioconcepto = 0
addrecientes.add(var.seccion)
finabrir2:
finabrir3:

END








