' Gambas module file


PUBLIC SUB abrir()
  DIM c AS String
DIM arr_cadenas AS String[]
DIM a AS Integer
DIM b AS Integer
DIM codigofinline AS String
DIM cuentaConcepto AS Integer

codigofinline = "|"
Dialog.Title = "Seleccione un archivo para abrir"
Dialog.Filter = ["", ""]
Dialog.Path = User.Name
Dialog.Filter = ["*.conceptos", "Datos de Conceptos"]

IF NOT Dialog.OpenFile() THEN
  TRY arr_cadenas = Split(File.LOAD(Dialog.Path), codigofinline)
 IF ERROR THEN 
      Message.Info("Error producido en la lectura del archivo ")
      GOTO finabreconcepto
      END IF
  
  
  
  IF arr_cadenas[0] = "v0.0.1" THEN 
       FMain.TextBoxRutaConcepto.text = Dialog.Path
        var.concepto_numero = Val(arr_cadenas[2]) 'numero de conceptos que contiene el archivo
          b = 2
        'amplio memoria de los proveedores
        'conceptos
      var.concepto_id.Resize(var.concepto_numero)
      var.concepto_idudobra.resize(var.concepto_numero) 'unidad de obra donde se encuentra
      var.concepto_nombre.resize(var.concepto_numero) 'nombre descriptivo unidad
      var.concepto_ud.Resize(var.concepto_numero)
      var.concepto_med.resize(var.concepto_numero) 'medicion
      var.concepto_precio.resize(var.concepto_numero)   'precio de contrato
      var.conceptomemoria.resize(var.concepto_numero)
      var.conceptotipo.resize(var.concepto_numero)
      var.concepto_Obra.resize(var.concepto_numero)
        
        
        
        'escribo datos de proveedores
        FOR a = 0 TO var.concepto_numero - 1
          b += 1
          var.concepto_id[a] = arr_cadenas[b]
          b += 1
          var.concepto_idudobra[a] = arr_cadenas[b]
          b += 1
          var.concepto_nombre[a] = arr_cadenas[b]
          b += 1 
          var.concepto_ud[a] = arr_cadenas[b]
          b += 1
          var.concepto_med[a] = arr_cadenas[b]
          b += 1
          var.concepto_precio[a] = arr_cadenas[b] 
          b += 1
          var.conceptotipo[a] = arr_cadenas[b]
          b += 1
          var.concepto_Obra[a] = arr_cadenas[b]
     NEXT
     FMain.TS1[2].Enabled = TRUE
      Message.Info("Archivo leido", "Aceptar") 
    
      ELSE
      Message.Error("Archivo no compatible con esta version", "Aceptar")
      GOTO finabreconcepto
      ENDIF 

END IF
finabreconcepto:
END

'--------------------------------------------------------------------------------
PUBLIC SUB salva(OPTIONAL ruta AS String, OPTIONAL sobreescribe AS String)
DIM lineas AS String
DIM destino AS String
DIM numArchivo AS Integer
DIM a AS Integer
DIM codigofinline AS String
DIM cuentaConcepto AS Integer

inicio:
var.esperaconcepto = "si"
IF ruta = "" THEN 
    Dialog.Title = "Escriba  un nombre de archivo para guardar los datos"
    Dialog.Filter = ["", ""]
    Dialog.Path = User.Name


    Dialog.Filter = ["*.conceptos", "Datos de conceptos"]
    a = Dialog.SaveFile()
    IF a = -1 THEN GOTO fins
 
        IF Right$(Dialog.Path, Len(".conceptos")) <> ".conceptos" THEN
        destino = Dialog.Path & ".conceptos"
        ELSE
        destino = Dialog.Path
        END IF
    
  
  ELSE 
  destino = ruta
  ENDIF 
  
  
    IF sobreescribe = "sobreescribe" THEN 
          GOTO finsobreescribe
          ENDIF
  
  'Comprueba si existe el archivo, en tal caso pide confirmacion de sobreescritura
  IF AbreGuardaProveedores.compruebaexistencia(DESTINO, "Conceptos") = 2 THEN 
  GOTO inicio
  END IF
  
  finsobreescribe:
  
  
  codigofinline = "|"
  lineas = "v0.0.1" & codigofinline 'informo version
  Lineas &= "gestionalmacen.090409" & codigofinline ' programa que ha echo el archivo
  cuentaConcepto = 0
  FOR a = 0 TO var.concepto_numero - 1
  IF var.concepto_id[a] <> "IdB" THEN cuentaConcepto += 1
  NEXT 
   
  Lineas &= Str$(cuentaConcepto) & codigofinline 'numero de conceptos que contiene el archivo sin estar borrados
  
  'escribo datos de proveedores
    FOR a = 0 TO var.concepto_numero - 1
      'PRINT var.Prov_id[a]; "IdB"; var.Prov_id[a] = "IdB"
        IF var.concepto_id[a] <> "IdB" THEN 
          'los datos borrados no los salvo
          Lineas &= var.concepto_id[a] & codigofinline
          Lineas &= var.concepto_idudobra[a] & codigofinline
          Lineas &= var.concepto_nombre[a] & codigofinline
          Lineas &= var.concepto_ud[a] & codigofinline
          Lineas &= var.concepto_med[a] & codigofinline
          Lineas &= var.concepto_precio[a] & codigofinline
          'Lineas &= var.conceptomemoria[a] & codigofinline
          Lineas &= var.conceptotipo[a] & codigofinline
          Lineas &= var.concepto_Obra[a] & codigofinline
          
        END IF
      NEXT
    
     IF destino = "" THEN 
     Message.Info("No se pudo salvar")
     GOTO fins
     ENDIF
    File.Save(destino, lineas)
     
    FMain.TextBoxRutaConcepto.text = destino
    
     IF sobreescribe = "sobreescribe" THEN 
  FMain.ProgressBarGuardar.value = FMain.ProgressBarGuardar.value + 0.33
    GOTO fins
    ENDIF 
          
    IF ruta <> "" THEN Message.Info("Archivo salvado", "Aceptar")
    
fins:    
 var.esperaconcepto = "" 
END
